SELECT * FROM login WHERE username = '$username'   41.112ms
SELECT username FROM login 						   8.844ms
INSERT INTO login VALUES('$username', '$password_new', '$type')" 31.154ms
DELETE FROM login where username = '$username' 38.823ms
UPDATE login SET password = '$password' WHERE username = '$id'" 15.906ms
SELECT type FROM login WHERE username = '$username' 27.667ms
CREATE VIEW T AS SELECT provnum AS provnum1, ROUND(AVG(score)::numeric, 2) AS user_score FROM feedback group by provnum1; CREATE VIEW U AS SELECT * FROM (provider_info LEFT OUTER JOIN T ON provider_info.provnum=t.provnum1);CREATE VIEW NH AS SELECT provnum, provname, overall_rating,survey_rating, quality_rating, staffing_rating,rn_staffing_rating,user_score FROM U WHERE UPPER(state) = UPPER('AL') ORDER BY overall_rating,survey_rating,quality_rating, staffing_rating,rn_staffing_rating,user_score DESC NULLS LAST, provnum DESC;SELECT * FROM NH;        382.893ms
CREATE VIEW T AS SELECT provnum AS provnum1, ROUND(AVG(score)::numeric, 2) AS user_score FROM feedback group by provnum1; CREATE VIEW U AS SELECT * FROM (provider_info LEFT OUTER JOIN T ON provider_info.provnum=t.provnum1);SELECT * FROM U WHERE provnum = '$provnum'   36.572ms
INSERT INTO feedback(username, provnum, score, score_desc) VALUES('$username', '$provnum', '$score', '$comment')  1.507ms
CREATE VIEW V2 AS SELECT provnum as provnum_copy, defpref, tag,survey_date_output, scope, defstat, statdate, cycle_no, standard,complaint FROM deficiencies ;CREATE VIEW V1 AS SELECT * FROM provider_info, V2 WHERE provnum = provnum_copy; 360.139ms
CREATE VIEW V1 AS SELECT * FROM feedback WHERE provnum = '$provnum' ORDER BY feedback_id;SELECT * FROM V1;  3.535ms
CREATE VIEW V1 AS SELECT provname, address, city, state, zip, phone, ownership, provnum, staffing_rating, rn_staffing_rating, aidhrd, vochrd, rnhrd, totlichrd, tothrd, pthrd, exp_aide, exp_lpn, exp_rn, exp_total, adj_aide, adj_lpn, adj_rn, adj_total, filedate FROM provider_info;SELECT * FROM V1 WHERE provnum = '$provnum'  18.043ms
CREATE VIEW V1 AS SELECT provnum, provname, address, city, state, zip, phone, ownership, filedate FROM provider_info;SELECT * from V1 WHERE provnum = '$provnum';SELECT penalty_date, penalty_type, fine_amt, payden_strt_dt, payden_days, filedate FROM penalties where provnum = '$provnum';  2.973ms;
SELECT tag_desc FROM deficiencies WHERE provnum='$provnum' AND survey_date_output='$date' AND tag = '$tag'  14.963ms 
INSERT INTO provider_info VALUES ($provnum, $provname, $address, $city, $state, $zip, $phone, $county_ssa, $county_name, $ownership, $bedcert, $restot, $certification , $inhosp, $lbn, $participation_date, $ccrc_facil, $sff, $oldsurvey, $chow_last_12mos, $resfamcouncil, $sprinkler_status, $overall_rating, $survey_rating, $quality_rating, $staffing_rating, $rn_staffing_rating, $aidhrd, $vochrd, $rnhrd, $totlichrd, $tothrd, $pthrd, $exp_aide, $exp_lpn, $exp_rn, $exp_total, $adj_aide, $adj_lpn, $adj_rn, $adj_total, $cycle_1_defs_score, $cycle_1_survey_date, $cycle_1_numrevis, $cycle_1_revisit_score, $cycle_1_total_score, $cycle_2_defs_score, $cycle_2_survey_date, $cycle_2_numrevis, $cycle_2_revisit_score, $cycle_2_total_score, $cycle_3_defs_score, $cycle_3_survey_date, $cycle_3_numrevis, $cycle_3_revisit_score, $cycle_3_total_score, $weighted_all_cycles_score, $incident_cnt, $cmplnt_cnt, $filedate);  1.505ms
INSERT INTO provider_info(provnum, provname, address, city, state, zip, phone, county_ssa, county_name, ownership, bedcert, restot, certification , inhosp, lbn, participation_date, ccrc_facil, sff, oldsurvey, chow_last_12mos, resfamcouncil, sprinkler_status, overall_rating, survey_rating, quality_rating, staffing_rating, rn_staffing_rating, aidhrd, vochrd, rnhrd, totlichrd, tothrd, pthrd, exp_aide, exp_lpn, exp_rn, exp_total, adj_aide, adj_lpn, adj_rn, adj_total, cycle_1_defs_score, cycle_1_survey_date, cycle_1_numrevis, cycle_1_revisit_score, cycle_1_total_score, cycle_2_defs_score, cycle_2_survey_date, cycle_2_numrevis, cycle_2_revisit_score, cycle_2_total_score, cycle_3_defs_score, cycle_3_survey_date, cycle_3_numrevis, cycle_3_revisit_score, cycle_3_total_score, weighted_all_cycles_score, incident_cnt, cmplnt_cnt, filedate) VALUES ('999999','NORTH HILL NURSING AND REHABILITATION CTR, LLC','200 NORTH PINE HILL ROAD','BIRMINGHAM','AL','35217','2058492352','360','Jefferson','For profit - Partnership',190,154,'Medicare and Medicaid','NO','NORTH HILL NURSING AND REHABILITATION CENTER, LLC','1968-07-01','N','N','N','N','Resident','Yes',2,2,4,3,3,2.35747,0.94448,0.62338,1.56786,3.92533,0.07435,2.42192,0.63659,1.01830,4.07681,2.38841,1.23143,0.45742,3.88112,16,'2016-01-28',1,0,16,88,'2014-12-04',1,0,88,28,'2014-02-05',1,0,28,42.000,0,5,'2017-01-01');
SELECT * from penalties WHERE provnum='$provnum' AND penalty_date > '$date';   2.233ms
SELECT * from deficiencies WHERE provnum='$provnum' AND survey_date_output> '$date'; 1.018ms
SELECT * from qualitymsrclaims WHERE provnum='$provnum';   50.285ms
SELECT * FROM (SELECT provnum, count(*) as penalty_count from penalties group by provnum) as foo WHERE foo.provnum='$provnum';  1.730ms
SELECT * from qualitymsrmds WHERE provnum='$provnum';  51.327ms
CREATE VIEW prov_agg_penalties AS SELECT sub1.provnum, penalty_count, total_fine, no_of_fines, no_of_payden FROM (SELECT provnum, count(*) as penalty_count,sum(fine_amt) as total_fine from penalties group by provnum) as sub1, (SELECT provnum, count(*) as no_of_fines FROM penalties WHERE penalty_type='Fine' group by provnum) as sub2, (SELECT provnum, count(*) as no_of_payden from penalties WHERE penalty_type='Payment Denial' group by provnum) as sub3 WHERE sub1.provnum=sub2.provnum AND sub2.provnum=sub3.provnum;  907.792ms
SELECT * from prov_agg_penalties where provnum='$provnum';  4.843ms
CREATE VIEW prov_agg_deficiencies AS SELECT sub1.provnum,sub1.cycle_no,total_deficiencies,standard_def,complaint_def, scope, scope_count FROM (SELECT provnum, cycle_no, count(*) as total_deficiencies FROM deficiencies GROUP BY provnum,cycle_no) as sub1, (SELECT provnum,cycle_no,count(*) as standard_def FROM deficiencies WHERE UPPER(standard) ='Y' GROUP BY provnum,cycle_no) as sub2, (SELECT provnum,cycle_no,count(*) as complaint_def FROM deficiencies WHERE UPPER(complaint) ='Y' GROUP BY provnum,cycle_no) as sub3, (SELECT provnum, cycle_no,scope, count(*) as scope_count FROM deficiencies GROUP BY provnum, cycle_no,scope) as sub4 WHERE sub1.provnum=sub2.provnum AND sub2.provnum=sub3.provnum AND sub3.provnum=sub4.provnum AND sub1.cycle_no=sub2.cycle_no AND sub2.cycle_no=sub3.cycle_no AND sub3.cycle_no=sub4.cycle_no;   39.534ms
SELECT * FROM prov_agg_deficiencies;  28.654ms
SELECT * FROM averages;  28.831ms
UPDATE provider_info SET phone='2545465456' where provnum='$provnum';  45.605ms
DELETE FROM provider_info WHERE provnum='$provnum'; 327.227ms
INSERT INTO deficiencies VALUES('$provnum', '$survey_date_output', '$SurveyType', '$defpref', '$tag', '$tag_desc', '$scope', '$defstat', '$statdate', '$cycle_no', '$standard', '$complaint', '$filedate') 53.935ms
INSERT INTO deficiencies VALUES('015009','2014-09-12','Health','F','0241','Provide care for residents in a way that maintains or improves their dignity and respect in full recognition of their individuality.','D','Deficient, Provider has date of correction','2014-10-16',3,'Y','N','2017-01-01');
DELETE FROM deficiencies WHERE provnum='$provnum' AND survey_date_output='$date' AND tag='$tag';  1.240ms 
INSERT INTO casper_contacts VALUES('$state','$email','$phone'); 41.548ms 'AL', 'amal.georgei@alabama.gov.in','2625208457' 
UPDATE casper_contacts SET phone='$phone' Where state='$state' AND email='$email'    1.035ms
DELETE FROM casper_contacts where state='$state' AND email='$email';  4.952ms
INSERT INTO ownership VALUES('$provnum', '$role_desc', '$owner_type', '$owner_name', '$owner_percent', '$association_date', '$filedate');  25.061ms      ('015009','5% OR GREATER DIRECT OWNERSHIP INTEREST','Individual','DEARMAN, LARRY','10%','since','2017-01-01')
UPDATE ownership SET role_desc='$role_desc', owner_percent='$owner_percent' where provnum='$provnum' AND association_date='since'; 39.427ms
DELETE FROM ownership WHERE provnum='$provnum' AND association_date='since'  26.438ms
SELECT * from stateavgs WHERE state='$state';  0.836ms
UPDATE stateavgs SET QM401='$qm401',QM402='$qm402',QM403='$qm403',QM404='$qm404',QM405='$qm405',QM406='$qm406',QM407='$qm407',QM408='$qm408',QM409='$qm409',QM410='$qm410',QM411='$qm411',QM415='$qm415',QM419='$qm419',QM424='$qm424',QM425='$qm425',QM426='$qm426',QM430='$qm430',QM434='$qm434',QM451='$qm451',QM452='$qm452',QM471='$qm471',QM521='$qm521',QM522='$qm522',QM523='$qm523' WHERE state='$state';  48.937ms
DELETE from stateavgs WHERE state='$state'; 1.144ms
INSERT INTO qualitymsrclaims VALUES('$provnum', '$msr_cd', '$msr_descr', '$stay_type', '$score_obs', '$score_exp', '$score_fin', '$extra', '$five_star_msr', '$measure_period', '$filedate);  17.872ms
'015009','521','Percentage of short-stay residents who were rehospitalized after a nursing home admission','Short Stay','21.923108','22.093023','22.962081',,'Y','2015Q1-2015Q4','2017-01-01'